### ISSUE TITLE
Haberler Ekranı

### ISSUE THREAD

**Issue by boduremre** [boduremre/Cuzdanim#5]
Newsapi kullanılarak haberler çekilmeli ve ekranda listelenmelidir. Haber detaylarını görmek için habere tıklandığında detaylar yeni bir ekranda gösterilmelidir.

**Comment by MSC-gh** [comment]
Haberler getirildi.

**Comment by MSC-gh** [comment]
Haber içeriği web tarayıcı kullanılarak getirildi.

**Comment by boduremre** [comment]
Haber ekranı test edildi. Test sonucunda haberler ve detayları başarılı bir şekilde getirildi.
